version: "3"
services:
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - elof_database:/var/lib/postgresql/data
    networks:
      nw:
        aliases:
          - database
  # bot:
  #   build: ./
  #   command: python main.py
  #   depends_on:
  #     - database
  #   networks:
  #     nw:
  #       aliases:
  #         - bot
networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database: